import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.desktop.html',
  styleUrls: ['./auto-generated.component.desktop.scss']
})
export class AutoGeneratedComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
