export const CURRENT_CONNECTION_ADDRESS = "CURRENT_CONNECTION_ADDRESS";
export const CURRENT_CONNECTION_PASSWORD = "CURRENT_CONNECTION_PASSWORD";
export const CONNECTION_HISTORY = "CONNECTION_HISTORY";
export const CURRENT_MOPIDY = "CURRENT_MOPIDY";
