import { NgModule } from "@angular/core";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { Routes } from "@angular/router";

// import { AutoGeneratedComponent } from "@src/app/auto-generated/auto-generated.component";
import { LayoutComponent } from "@src/app/layout/layout.component";

export const routes: Routes = [
	// {
	// 	path: "",
	// 	redirectTo: "/players",
	// 	pathMatch: "full",
	// },
	{
		path: "",
		pathMatch: "full",
		redirectTo: "/library",
	},
	{
		path: "library",
		component: LayoutComponent,
	// tslint:disable-next-line:newline-per-chained-call
		loadChildren: () => import("@src/app/content/content.module").then((m) => m.ContentModule),
	},
	// {
	// 	path: "auto-generated",
	// 	component: AutoGeneratedComponent,
	// },
];

@NgModule({
	imports: [NativeScriptRouterModule.forRoot(routes)],
	exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
