import { NgModule } from "@angular/core";
import { Routes, RouterModule } from "@angular/router";

import { AutoGeneratedComponent } from "@src/app/auto-generated/auto-generated.component";


export const routes: Routes = [
	{ path: "index.electron.html", redirectTo: "", pathMatch: "full" },
	{ path: "", component: AutoGeneratedComponent },
];


@NgModule({
	imports: [RouterModule.forRoot(routes)],
	exports: [RouterModule],
})
export class AppRoutingModule { }
