import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { FormsModule } from "@angular/forms";

import { AppRoutingModule } from "@src/app/app-routing.module";
import { AppComponent } from "@src/app/app.component";

import { MatIconModule } from "@angular/material/icon";
import { MatToolbarModule } from "@angular/material/toolbar";
import { MatFormFieldModule } from "@angular/material/form-field";
import { MatInputModule } from "@angular/material/input";
import { MatButtonModule } from "@angular/material/button";
import { MatSidenavModule } from "@angular/material/sidenav";
import { MatListModule } from "@angular/material/list";
import { MatDividerModule } from "@angular/material/divider";
import { MatSelectModule } from "@angular/material/select";
import { MatExpansionModule } from "@angular/material/expansion";
import { MatButtonToggleModule } from "@angular/material/button-toggle";
import { MatMenuModule } from "@angular/material/menu";
import { MatSliderModule } from "@angular/material/slider";
import { MatDialogModule } from "@angular/material/dialog";
import { MatTooltipModule, MAT_TOOLTIP_DEFAULT_OPTIONS, MatTooltipDefaultOptions } from "@angular/material/tooltip";
import { MatGridListModule } from "@angular/material/grid-list";

import { SharedModule } from "@src/app/shared/shared.module";
import { ConnectComponent } from "@src/app/connect/connect.component";
import { NavbarComponent } from "@src/app/navbar/navbar.component";
import { PlaybackComponent } from "@src/app/playback/playback.component";
import { AutoGeneratedComponent } from "@src/app/auto-generated/auto-generated.component";
import { LayoutComponent } from '@src/app/layout/layout.component';


export const TOOLTIP_OPTIONS: MatTooltipDefaultOptions = {
	showDelay: 500,
	hideDelay: 1500,
	touchendHideDelay: 1500,
};


@NgModule({
	declarations: [
		ConnectComponent,
		AppComponent,
		NavbarComponent,
		PlaybackComponent,
		AutoGeneratedComponent,
		LayoutComponent,
	],
	imports: [
		BrowserModule,
		AppRoutingModule,
		CommonModule,
		BrowserAnimationsModule,
		FormsModule,
		SharedModule,
		MatIconModule,
		MatToolbarModule,
		MatFormFieldModule,
		MatInputModule,
		MatButtonModule,
		MatSidenavModule,
		MatListModule,
		MatDividerModule,
		MatSelectModule,
		MatExpansionModule,
		MatButtonToggleModule,
		MatMenuModule,
		MatSliderModule,
		MatDialogModule,
		MatTooltipModule,
		MatGridListModule,
	],
	providers: [
		{ provide: MAT_TOOLTIP_DEFAULT_OPTIONS, useValue: TOOLTIP_OPTIONS },
	],
	bootstrap: [AppComponent]
})
export class AppModule { }
